# Generated by Django 5.0.7 on 2024-09-12 07:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('borrower_type', models.CharField(choices=[('INDIVIDUAL', 'Individual'), ('COMPANY', 'Company')], max_length=32)),
                ('full_name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('identification_number', models.CharField(max_length=64, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('INACTIVE', 'Inactive'), ('BLACKLISTED', 'Blacklisted')], default='ACTIVE', max_length=32)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_borrowers', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_borrowers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Borrower',
                'verbose_name_plural': 'Borrowers',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='BorrowerDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('document_type', models.CharField(max_length=64)),
                ('document_number', models.CharField(max_length=128)),
                ('document_file', models.FileField(upload_to='borrower_documents/')),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('issued_date', models.DateField(blank=True, null=True)),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='borrowers.borrower')),
            ],
            options={
                'verbose_name': 'Borrower Document',
                'verbose_name_plural': 'Borrower Documents',
                'ordering': ['document_type'],
            },
        ),
        migrations.CreateModel(
            name='BorrowerFinancialInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('annual_income', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('credit_score', models.IntegerField(blank=True, null=True)),
                ('total_outstanding_debt', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('total_loans', models.IntegerField(default=0)),
                ('borrower', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='financial_info', to='borrowers.borrower')),
            ],
            options={
                'verbose_name': 'Borrower Financial Info',
                'verbose_name_plural': 'Borrower Financial Infos',
            },
        ),
    ]
