# Generated by Django 5.0.7 on 2024-09-12 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='is_over_due',
            field=models.BooleanField(default=False),
        ),
    ]
