# Generated by Django 5.0.7 on 2024-09-10 22:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anons', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anons',
            name='read_by',
            field=models.ManyToManyField(blank=True, null=True, related_name='read_anons', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='AnonsReader',
        ),
    ]
