# Generated by Django 5.0.7 on 2024-09-11 10:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anons', '0002_anons_read_by_delete_anonsreader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='anons',
            name='read_by',
            field=models.ManyToManyField(related_name='read_anons', to=settings.AUTH_USER_MODEL),
        ),
    ]
