# Generated by Django 5.0.7 on 2024-08-30 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_ru',
            field=models.CharField(max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_uz',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
